# Generated by Django 4.0 on 2023-04-07 22:38

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('STG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTreatmentGuidelineTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level1Heading', models.CharField(blank=True, max_length=255)),
                ('Level2Heading', models.CharField(blank=True, max_length=255)),
                ('Level3Heading', models.CharField(blank=True, max_length=255)),
                ('BackgroundAndClinicalFeatures', django_quill.fields.QuillField(blank=True)),
                ('Tests', django_quill.fields.QuillField(blank=True)),
                ('Notes', models.TextField(blank=True)),
                ('TreatmentNotes', django_quill.fields.QuillField(blank=True)),
                ('Pharmacy', django_quill.fields.QuillField(blank=True)),
                ('Complications', django_quill.fields.QuillField(blank=True)),
                ('Prevention', django_quill.fields.QuillField(blank=True)),
                ('GuidelineName', models.CharField(blank=True, max_length=255)),
                ('Year_of_Publication', models.IntegerField(default=2020)),
            ],
        ),
        migrations.DeleteModel(
            name='FirstTopic',
        ),
    ]
