# Generated by Django 4.0 on 2023-04-07 22:47

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('STG', '0002_standardtreatmentguidelinetopic_delete_firsttopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtreatmentguidelinetopic',
            name='Complications',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='standardtreatmentguidelinetopic',
            name='Pharmacy',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='standardtreatmentguidelinetopic',
            name='Prevention',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='standardtreatmentguidelinetopic',
            name='Tests',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='standardtreatmentguidelinetopic',
            name='TreatmentNotes',
            field=django_quill.fields.QuillField(),
        ),
    ]
