# Generated by Django 4.0 on 2023-04-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STG', '0004_level1heading_level2heading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level1heading',
            old_name='Level1Heading',
            new_name='Level_1_Heading',
        ),
        migrations.RenameField(
            model_name='level2heading',
            old_name='Level2Heading',
            new_name='Level_2_Heading',
        ),
        migrations.RenameField(
            model_name='standardtreatmentguidelinetopic',
            old_name='Level1Heading',
            new_name='Level_1_Heading',
        ),
        migrations.RenameField(
            model_name='standardtreatmentguidelinetopic',
            old_name='Level2Heading',
            new_name='Level_2_Heading',
        ),
    ]
