# Generated by Django 4.0 on 2023-04-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STG', '0005_rename_level1heading_level1heading_level_1_heading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardtreatmentguidelinetopic',
            old_name='Level_1_Heading',
            new_name='firstLevelHeading',
        ),
        migrations.RenameField(
            model_name='standardtreatmentguidelinetopic',
            old_name='Level_2_Heading',
            new_name='secondLevelHeading',
        ),
    ]
