# Generated by Django 4.0 on 2023-04-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STG', '0006_rename_level_1_heading_standardtreatmentguidelinetopic_firstlevelheading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level1heading',
            old_name='Level_1_Heading',
            new_name='firstLevelHeading',
        ),
        migrations.RenameField(
            model_name='level2heading',
            old_name='Level_2_Heading',
            new_name='secondLevelHeading',
        ),
    ]
