# Generated by Django 4.0 on 2023-04-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STG', '0008_alter_standardtreatmentguidelinetopic_backgroundandclinicalfeatures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level2heading',
            name='firstLevelHeading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='STG.level1heading'),
        ),
    ]
